---
title: "opgaver"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
Sys.setenv(language = "en")
library(quantmod)
library(rugarch)
```



# Exercise 2

```{r}
getSymbols("^GSPC", from = "2005-01-01", to = "2014-12-31", src = "yahoo")

sp500 <- xts( diff( log( GSPC[,6] ) )[-1] )
y <- as.numeric(sp500)
result_object <- ugarchspec(variance.model = list(model = "sGARCH",
                                                  garchOrder = c(1,1)),
                            mean.model = list(armaOrder = c(2,0)),
                            distribution.model = "norm")
garch_est <- ugarchfit(spec = result_object, data = y)
# opgave 1
acf(y)
acf(y^2)

result_object <- ugarchspec(variance.model = list(model = "sGARCH",
                                                  garchOrder = c(0,2)),
                            mean.model = list(armaOrder = c(3,0)),
                            distribution.model = "norm")
garch_est <- ugarchfit(spec = result_object, data = y)



```

